import type {
  IAddress,
  IInvoice,
  IVendor,
} from "../types/server/server.interfaces";

export const MOCK_INVOICE_LIST: IInvoice[] = [
  {
    id: "inv_101",
    vendor_id: "vend_01",
    invoice_number: "INV-2026-001",
    amount: 1500.0,
    currency: "GBP",
    status: "overdue",
  },
  {
    id: "inv_102",
    vendor_id: "vend_02",
    invoice_number: "INV-2026-002",
    amount: 2450.5,
    currency: "GBP",
    status: "draft",
  },
  {
    id: "inv_103",
    vendor_id: "vend_03",
    invoice_number: "INV-2026-003",
    amount: 120.0,
    currency: "GBP",
    status: "paid",
  },
  {
    id: "inv_104",
    vendor_id: "vend_04",
    invoice_number: "INV-2026-004",
    amount: 8900.0,
    currency: "GBP",
    status: "open",
  },
  {
    id: "inv_105",
    vendor_id: "vend_05",
    invoice_number: "INV-2026-005",
    amount: 310.25,
    currency: "GBP",
    status: "paid",
  },
  {
    id: "inv_106",
    vendor_id: "vend_06",
    invoice_number: "INV-2026-006",
    amount: 55.0,
    currency: "GBP",
    status: "sent",
  },
  {
    id: "inv_107",
    vendor_id: "vend_07",
    invoice_number: "INV-2026-007",
    amount: 1200.0,
    currency: "GBP",
    status: "void",
  },
  {
    id: "inv_108",
    vendor_id: "vend_08",
    invoice_number: "INV-2026-008",
    amount: 430.0,
    currency: "GBP",
    status: "paid",
  },
  {
    id: "inv_109",
    vendor_id: "vend_09",
    invoice_number: "INV-2026-009",
    amount: 2100.0,
    currency: "GBP",
    status: "sent",
  },
  {
    id: "inv_110",
    vendor_id: "vend_10",
    invoice_number: "INV-2026-010",
    amount: 750.0,
    currency: "GBP",
    status: "overdue",
  },
];

export const MOCK_VENDOR_LIST: IVendor[] = [
  {
    id: "vend_01",
    name: "Apex Logistics",
    address_id: "addr_01",
    vat_number: "GB111222333",
    account_number: "10000001",
    new_vendor: false,
    rating: 4.8,
  },
  {
    id: "vend_02",
    name: "Global Tech Solutions",
    address_id: "addr_02",
    vat_number: "GB222333444",
    account_number: "20000002",
    new_vendor: true,
    rating: 3.5,
  },
  {
    id: "vend_03",
    name: "Swift Office Supplies",
    address_id: "addr_03",
    vat_number: "GB333444555",
    account_number: "30000003",
    new_vendor: false,
    rating: 4.2,
  },
  {
    id: "vend_04",
    name: "Blue Horizon Energy",
    address_id: "addr_04",
    vat_number: "GB444555666",
    account_number: "40000004",
    new_vendor: false,
    rating: 4.9,
  },
  {
    id: "vend_05",
    name: "Northern Catering Co",
    address_id: "addr_05",
    vat_number: "GB555666777",
    account_number: "50000005",
    new_vendor: true,
    rating: 2.8,
  },
  {
    id: "vend_06",
    name: "Precision Engineering",
    address_id: "addr_06",
    vat_number: "GB666777888",
    account_number: "60000006",
    new_vendor: false,
    rating: 4.5,
  },
  {
    id: "vend_07",
    name: "Delta Consulting",
    address_id: "addr_07",
    vat_number: "GB777888999",
    account_number: "70000007",
    new_vendor: false,
    rating: 4.0,
  },
  {
    id: "vend_08",
    name: "Starlight Marketing",
    address_id: "addr_08",
    vat_number: "GB888999000",
    account_number: "80000008",
    new_vendor: true,
    rating: 3.9,
  },
  {
    id: "vend_09",
    name: "Summit Real Estate",
    address_id: "addr_09",
    vat_number: "GB999000111",
    account_number: "90000009",
    new_vendor: false,
    rating: 4.7,
  },
  {
    id: "vend_10",
    name: "Velocity Freight",
    address_id: "addr_10",
    vat_number: "GB000111222",
    account_number: "10000010",
    new_vendor: false,
    rating: 4.1,
  },
];

export const MOCK_ADDRESS_LIST: IAddress[] = [
  {
    id: "addr_012",
    line_1: "10 Downing Street",
    city: "London",
    postcode: "SW1A 2AA",
    country: "United Kingdom",
  },
  {
    id: "addr_02",
    line_1: "42 Wallaby Way",
    city: "Manchester",
    postcode: "M1 1AA",
    country: "United Kingdom",
  },
  {
    id: "addr_03",
    line_1: "15 Baker Street",
    city: "London",
    postcode: "NW1 6XE",
    country: "United Kingdom",
  },
  {
    id: "addr_04",
    line_1: "88 Skyline Tower",
    city: "Birmingham",
    postcode: "B1 1BB",
    country: "United Kingdom",
  },
  {
    id: "addr_05",
    line_1: "5 High Street",
    city: "Edinburgh",
    postcode: "EH1 1YZ",
    country: "United Kingdom",
  },
  {
    id: "addr_06",
    line_1: "Industrial Park A",
    city: "Leeds",
    postcode: "LS1 2CC",
    country: "United Kingdom",
  },
  {
    id: "addr_07",
    line_1: "The Glass House",
    city: "Bristol",
    postcode: "BS1 3DD",
    country: "United Kingdom",
  },
  {
    id: "addr_08",
    line_1: "99 Media City",
    city: "Salford",
    postcode: "M50 2EQ",
    country: "United Kingdom",
  },
  {
    id: "addr_09",
    line_1: "7 Peak View",
    city: "Sheffield",
    postcode: "S1 4FF",
    country: "United Kingdom",
  },
  {
    id: "addr_10",
    line_1: "Docklands Hub",
    city: "Liverpool",
    postcode: "L1 5GG",
    country: "United Kingdom",
  },
];
