import type { IInvoice } from "../types/server/server.interfaces";

export const MOCK_INVOICE_LIST: IInvoice[] = [
  {
    id: "inv-001",
    invoice_number: "XEL-9901",
    amount: 1250.5,
    currency: "GBP",
    status: "open",
    vendor: {
      id: "v-101",
      name: "Global Tech Solutions",
      vat_number: "GB123456789",
      account_number: "88776655",
      new_vendor: false,
      rating: 95,
      address: {
        line_1: "12 High Street",
        city: "London",
        postcode: "EC1A 1BB",
        country: "United Kingdom",
      },
    },
  },
  {
    id: "inv-002",
    invoice_number: "XEL-9902",
    amount: 450.0,
    currency: "USD",
    status: "paid",
    vendor: {
      id: "v-102",
      name: "Alpha Logistics",
      vat_number: "US998877665",
      account_number: "11223344",
      new_vendor: true,
      rating: 40,
      address: {
        line_1: "500 Madison Ave",
        city: "New York",
        postcode: "10022",
        country: "USA",
      },
    },
  },
  {
    id: "inv-003",
    invoice_number: "XEL-9903",
    amount: 3200.0,
    currency: "EUR",
    status: "overdue",
    vendor: {
      id: "v-103",
      name: "Berlin Bau GmbH",
      vat_number: "DE554433221",
      account_number: "55443322",
      new_vendor: false,
      rating: 88,
      address: {
        line_1: "Friedrichstraße 12",
        city: "Berlin",
        postcode: "10117",
        country: "Germany",
      },
    },
  },
  {
    id: "inv-004",
    invoice_number: "XEL-9904",
    amount: 89.99,
    currency: "GBP",
    status: "draft",
    vendor: {
      id: "v-104",
      name: "Pantry & Co",
      vat_number: "GB990011223",
      account_number: "99001122",
      new_vendor: false,
      rating: 72,
      address: {
        line_1: "45 Market Lane",
        city: "Manchester",
        postcode: "M1 1WR",
        country: "United Kingdom",
      },
    },
  },
  {
    id: "inv-005",
    invoice_number: "XEL-9905",
    amount: 15600.0,
    currency: "GBP",
    status: "sent",
    vendor: {
      id: "v-105",
      name: "Heavy Machinery Ltd",
      vat_number: "GB556677889",
      account_number: "44332211",
      new_vendor: true,
      rating: 25,
      address: {
        line_1: "Industrial Unit 4",
        city: "Birmingham",
        postcode: "B1 1QU",
        country: "United Kingdom",
      },
    },
  },
  {
    id: "inv-006",
    invoice_number: "XEL-9906",
    amount: 210.45,
    currency: "EUR",
    status: "void",
    vendor: {
      id: "v-106",
      name: "Petit Café",
      vat_number: "FR112233445",
      account_number: "12312312",
      new_vendor: false,
      rating: 98,
      address: {
        line_1: "10 Rue de Rivoli",
        city: "Paris",
        postcode: "75001",
        country: "France",
      },
    },
  },
  {
    id: "inv-007",
    invoice_number: "XEL-9907",
    amount: 740.0,
    currency: "USD",
    status: "open",
    vendor: {
      id: "v-107",
      name: "Cloud Services Inc",
      vat_number: "US445566778",
      account_number: "98765432",
      new_vendor: false,
      rating: 91,
      address: {
        line_1: "1 Infinite Loop",
        city: "Cupertino",
        postcode: "95014",
        country: "USA",
      },
    },
  },
  {
    id: "inv-008",
    invoice_number: "XEL-9908",
    amount: 12.0,
    currency: "GBP",
    status: "paid",
    vendor: {
      id: "v-108",
      name: "Local Office Supplies",
      vat_number: "GB887766554",
      account_number: "55664433",
      new_vendor: false,
      rating: 60,
      address: {
        line_1: "Station Road",
        city: "Reading",
        postcode: "RG1 1JX",
        country: "United Kingdom",
      },
    },
  },
  {
    id: "inv-009",
    invoice_number: "XEL-9909",
    amount: 4500.0,
    currency: "EUR",
    status: "overdue",
    vendor: {
      id: "v-109",
      name: "Iberia Export",
      vat_number: "ES667788990",
      account_number: "11223355",
      new_vendor: true,
      rating: 15,
      address: {
        line_1: "Calle Mayor 5",
        city: "Madrid",
        postcode: "28013",
        country: "Spain",
      },
    },
  },
  {
    id: "inv-010",
    invoice_number: "XEL-9910",
    amount: 300.0,
    currency: "GBP",
    status: "open",
    vendor: {
      id: "v-110",
      name: "Quick Print",
      vat_number: "GB332211004",
      account_number: "00998877",
      new_vendor: false,
      rating: 85,
      address: {
        line_1: "Print House",
        city: "Bristol",
        postcode: "BS1 1AA",
        country: "United Kingdom",
      },
    },
  },
  {
    id: "inv-011",
    invoice_number: "XEL-9911",
    amount: 920.5,
    currency: "USD",
    status: "sent",
    vendor: {
      id: "v-111",
      name: "Marketing Pro",
      vat_number: "US554466221",
      account_number: "77665544",
      new_vendor: false,
      rating: 77,
      address: {
        line_1: "Michigan Ave",
        city: "Chicago",
        postcode: "60601",
        country: "USA",
      },
    },
  },
  {
    id: "inv-012",
    invoice_number: "XEL-9912",
    amount: 6100.0,
    currency: "GBP",
    status: "paid",
    vendor: {
      id: "v-112",
      name: "Recruit Direct",
      vat_number: "GB114477882",
      account_number: "33221144",
      new_vendor: false,
      rating: 90,
      address: {
        line_1: "Corporate Plaza",
        city: "Leeds",
        postcode: "LS1 4DY",
        country: "United Kingdom",
      },
    },
  },
  {
    id: "inv-013",
    invoice_number: "XEL-9913",
    amount: 150.25,
    currency: "EUR",
    status: "open",
    vendor: {
      id: "v-113",
      name: "Vinho & Co",
      vat_number: "PT112244556",
      account_number: "22334411",
      new_vendor: true,
      rating: 55,
      address: {
        line_1: "Av. da Liberdade",
        city: "Lisbon",
        postcode: "1250-096",
        country: "Portugal",
      },
    },
  },
  {
    id: "inv-014",
    invoice_number: "XEL-9914",
    amount: 2500.0,
    currency: "GBP",
    status: "overdue",
    vendor: {
      id: "v-114",
      name: "Apex Security",
      vat_number: "GB554422110",
      account_number: "88997766",
      new_vendor: false,
      rating: 82,
      address: {
        line_1: "Security House",
        city: "Liverpool",
        postcode: "L1 1JX",
        country: "United Kingdom",
      },
    },
  },
  {
    id: "inv-015",
    invoice_number: "XEL-9915",
    amount: 10500.0,
    currency: "USD",
    status: "draft",
    vendor: {
      id: "v-115",
      name: "Silicon Valley Data",
      vat_number: "US991188227",
      account_number: "44553322",
      new_vendor: true,
      rating: 30,
      address: {
        line_1: "Palo Alto Way",
        city: "San Jose",
        postcode: "95113",
        country: "USA",
      },
    },
  },
  {
    id: "inv-016",
    invoice_number: "XEL-9916",
    amount: 55.0,
    currency: "GBP",
    status: "paid",
    vendor: {
      id: "v-116",
      name: "The Flower Shop",
      vat_number: "GB121234345",
      account_number: "12345612",
      new_vendor: false,
      rating: 100,
      address: {
        line_1: "Green Lane",
        city: "Oxford",
        postcode: "OX1 1HB",
        country: "United Kingdom",
      },
    },
  },
  {
    id: "inv-017",
    invoice_number: "XEL-9917",
    amount: 120.0,
    currency: "EUR",
    status: "open",
    vendor: {
      id: "v-117",
      name: "Design Studio Milano",
      vat_number: "IT889900112",
      account_number: "11221122",
      new_vendor: false,
      rating: 89,
      address: {
        line_1: "Via Torino 15",
        city: "Milan",
        postcode: "20123",
        country: "Italy",
      },
    },
  },
  {
    id: "inv-018",
    invoice_number: "XEL-9918",
    amount: 275.5,
    currency: "GBP",
    status: "sent",
    vendor: {
      id: "v-118",
      name: "Cleaners R Us",
      vat_number: "GB665544331",
      account_number: "99881122",
      new_vendor: false,
      rating: 65,
      address: {
        line_1: "Oak Yard",
        city: "Sheffield",
        postcode: "S1 2GU",
        country: "United Kingdom",
      },
    },
  },
  {
    id: "inv-019",
    invoice_number: "XEL-9919",
    amount: 8000.0,
    currency: "USD",
    status: "void",
    vendor: {
      id: "v-119",
      name: "Boston Consulting",
      vat_number: "US118833774",
      account_number: "55441199",
      new_vendor: false,
      rating: 94,
      address: {
        line_1: "Beacon St",
        city: "Boston",
        postcode: "02108",
        country: "USA",
      },
    },
  },
  {
    id: "inv-020",
    invoice_number: "XEL-9920",
    amount: 420.0,
    currency: "GBP",
    status: "open",
    vendor: {
      id: "v-120",
      name: "Northern Power",
      vat_number: "GB778811229",
      account_number: "33445566",
      new_vendor: true,
      rating: 50,
      address: {
        line_1: "Energy Way",
        city: "Newcastle",
        postcode: "NE1 1DE",
        country: "United Kingdom",
      },
    },
  },
];
